import React, { useState } from "react";

function NewPlantForm() {
  const [formData, setFormData] = useState({
    name: "",
    image: "",
    price: "",
  });
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [successMessage, setSuccessMessage] = useState("");

  function handleChange(e) {
    const { name, value } = e.target;

    // set form data
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  }

  const handleSubmit = async (e) => {
    e.preventDefault(); // Prevent the default form submission behavior

    setIsLoading(true);
    setError(null);
    setSuccessMessage("");

    try {
      const response = await fetch("http://localhost:6001/plants", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        throw new Error("Network response was not ok.");
      }

      const newPlant = await response.json();

      // The 'newPlant' object wil contains an ID generated by the server.
      console.log("Successfully created plant:", newPlant);

      setSuccessMessage(
        `Plant "${newPlant.name}" created with ID: ${newPlant.id}`
      );
      setFormData({ name: "", image: "", price: "" }); // Clear the form
    } catch (err) {
      setError(err);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="new-plant-form">
      <h2>New Plant</h2>

      {successMessage && <p style={{ color: "green" }}>{successMessage}</p>}
      {error && <p style={{ color: "red" }}>Error: {error.message}</p>}

      <form onSubmit={handleSubmit}>
        <input
          type="text"
          name="name"
          placeholder="Plant name"
          value={formData.name}
          onChange={handleChange}
          disabled={isLoading}
        />
        <input
          type="text"
          name="image"
          placeholder="Image URL"
          value={formData.image}
          onChange={handleChange}
          disabled={isLoading}
        />
        <input
          type="number"
          name="price"
          step="0.01"
          placeholder="Price"
          value={formData.price}
          onChange={handleChange}
          disabled={isLoading}
        />
        <button type="submit" disabled={isLoading}>
          {isLoading ? "Adding Plant..." : "Add Plant"}
        </button>
      </form>
    </div>
  );
}

export default NewPlantForm;
